import { ReactNode } from "react";
import Head from "next/head";
import { Heebo } from "@next/font/google";

import { Header } from "components/Header";
import * as S from "./styled";

const lang = Heebo({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});

export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <S.Container className={lang.className}>
      <Head>
        <title>Merito</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </S.Container>
  );
};
